# basic options, I can say whatever here.
title: Sen Wang
author: Sen Wang
email: senwang2016@gmail.com
description: 2019 all rights reserved.
twitter_username: swang
github_username:  senwang2018

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
